create table if not exists public."Users" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  username varchar not null unique,
  password varchar not null,
  name varchar
);

create table if not exists public."Votes" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id bigint not null references public."Users"(id) on delete cascade,
  voted_pokemon bigint not null
);

alter table public."Users" enable row level security;
alter table public."Votes" enable row level security;

create policy "Allow public reads for simple login demo"
on public."Users"
for select
to anon
using (true);

create policy "Allow public inserts for simple signup demo"
on public."Users"
for insert
to anon
with check (true);

create policy "Allow public vote reads"
on public."Votes"
for select
to anon
using (true);

create policy "Allow public vote inserts"
on public."Votes"
for insert
to anon
with check (true);
